FROM node:16 as build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 3000
ENV REACT_APP_BACKEND_URL=http://ec2-18-179-40-50.ap-northeast-1.compute.amazonaws.com:8080
RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html