services:
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    hostname: mysqldb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  spring:
    depends_on:
      - mysqldb
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: web_phpmyadmin
    restart: always
    ports:
      - 8888:8888
    environment:
      - PMA_HOST=mysqldb
      - APACHE_PORT=8888

  frontend:
    image: albertkingdomdevelop/frontend-v2
    ports:
      - 80:80

volumes:
  db:
