-- Flyway baseline: current schema as generated by Hibernate ddl-auto=update.
--
-- This migration recreates the pre-Flyway schema so that a fresh database can
-- boot into the same state, and so that `spring.jpa.hibernate.ddl-auto=validate`
-- has something to validate against. For existing databases, Flyway is
-- configured with baseline-on-migrate=true and will mark this migration as
-- applied without running it.
--
-- All future schema changes go into V2, V3, ... and must never modify this file
-- once merged (Flyway rejects checksum mismatches on already-applied
-- migrations). See docs/database-migration.md for the workflow.

CREATE TABLE users (
    id       BIGINT       NOT NULL AUTO_INCREMENT,
    email    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_email (email)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE roles (
    id   BIGINT       NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE users_roles (
    users_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    KEY ix_users_roles_users (users_id),
    KEY ix_users_roles_roles (roles_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT fk_users_roles_role FOREIGN KEY (roles_id) REFERENCES roles (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE product (
    id       BIGINT       NOT NULL AUTO_INCREMENT,
    img_name VARCHAR(255) DEFAULT NULL,
    img_url  VARCHAR(255) DEFAULT NULL,
    name     VARCHAR(255) DEFAULT NULL,
    price    FLOAT        DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE orders (
    id         BIGINT        NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6)   DEFAULT NULL,
    order_id   BINARY(255)   DEFAULT NULL,
    price_sum  FLOAT         DEFAULT NULL,
    user_id    BIGINT        DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE order_item (
    id         BIGINT NOT NULL AUTO_INCREMENT,
    order_id   BIGINT DEFAULT NULL,
    product_id BIGINT DEFAULT NULL,
    quantity   INT    DEFAULT NULL,
    PRIMARY KEY (id),
    KEY ix_order_item_order (order_id),
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
